version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: scraper-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: scraper_user
      POSTGRES_PASSWORD: scraper_password
      POSTGRES_DB: scraper_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 